services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - quickpay-local-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d paymentsdb" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  quickpay-local-db-data: