spring.application.name=payments
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
logging.level.root=INFO
logging.level.com.progressoft.payments=DEBUG
payments.notes-max-length=500
payments.allowed-currencies=JOD,USD,EUR
payments.persist-db-on-error=false
payments.default-template-name=default