spring.application.name=payments
logging.level.root=INFO
logging.level.com.progressoft.payments=DEBUG
payments.notes-max-length=500
payments.allowed-currencies=JOD,USD,EUR
payments.persist-db-on-error=false
payments.default-template-name=default